### PR TITLE
Add reporting of 99th and 99.9th percentile latency

### PR DESCRIPTION
**Pull request by charleskorn-x**
This adds reporting of the 99th and 99.9th percentile latencies to all report types.

### CODE REVIEW

**Comment by AntyaDev** [comment]
Hi @charleskorn-x you missed to update TXT report also.
Now I think maybe it does make sense to drop 95% completely since we have 99% 99.9%

**Comment by AntyaDev** [comment]
I close it till the release of v1 and then we reopen it

**Comment by charleskorn-x** [comment]
Hi @AntyaDev, I'm a little confused by your comment about the TXT report - is that not covered by https://github.com/PragmaticFlow/NBomber/pull/226/files#diff-3f021a8b43760817efea6816efd069a2?

**Comment by AntyaDev** [comment]
Sorry @charleskorn-x, you are right, I missed that file. I want to think a bit about this functionality since it probably better to have as configuration.

**Pull request closed without merging**
