### PR TITLE
added md report

### PR DESCRIPTION
**Pull request by Yaroshvitaliy**

### CODE REVIEW

**Comment by vilinski** [comment]
Would it be possible to make md tables more readable (looking more like a txt variant)?

**Comment by Yaroshvitaliy** [comment]
> Would it be possible to make md tables more readable (looking more like a txt variant)?

Yes, it's possible, but it will bring unnecessary complexity to code (we will have to find out the width of each column and add extra symbols).
I did my best to keep the code as simple as possible.
Why do we need read md like txt format?

**Comment by vilinski** [comment]
because md IS a text format, otherwise html is just enough

**Comment by Yaroshvitaliy** [comment]
> otherwise html is just enough

Both html and txt are not enough. 
Md is used as attachments in systems where md format is supported (like readme.md in git). Compact mode of md is appropriate in this case.

@AntyaDev what do you think?

**Comment by AntyaDev** [comment]
I close it till the release of v1 and then we reopen it

**Pull request closed without merging**
