### PR TITLE
feat: PsPingPlugin added

### PR DESCRIPTION
**Pull request by deyanp**
Did not really find unit tests for PingPlugin, so not sure what/how such should be created for PsPingPlugin ...

### CODE REVIEW

**Comment by AntyaDev** [comment]
@deyanp
I think that later we can add UDP support too :)

**Comment by AntyaDev** [comment]
@deyanp I am just thinking: does it make sense to make a few calls and then take the average result? I guess that PsPing is behaving like this since it has a histogram and warmup
https://docs.microsoft.com/en-us/sysinternals/downloads/psping

**Comment by deyanp** [comment]
> does it make sense to make a few calls and then take the average result?

@AntyaDev, yes, 100%, I was actually surprised that it only makes a single call (which is very unreliable). How can that be done?

**Comment by AntyaDev** [comment]
I think in case you don't have a timeout on the first call:
- you can retry this call via Arrar.map
- use Array.average

another way is to provide some percentiles but it can be used later, for now I think it's ok to use average

**Comment by deyanp** [comment]
@AntyaDev is it possible to make multiple pings *during* the load tests execution?

**Comment by AntyaDev** [comment]
I think that ping logic should be executed sequential to get the most correct results

**Comment by deyanp** [comment]
You are right.  I will make the number of executions configurable, default to 4. 

I guess this PR is already closed, so I need to submit a new PR?

**Comment by AntyaDev** [comment]
yes, better new PR

**Pull request merged**
